### ISSUE TITLE
Direct data use

### ISSUE THREAD

**Issue by countnazgul** [switchnick/nodejs-qliksense#1]
Is there any way the data to be received without going through "index.html"?
The idea is to get the data directly from hypercube (not the visualsization) in nodejs and use it?

Thanks!
Stefan

**Comment by websy85** [comment]
Hi Stefan, 
Yes, you can work with data directly and even do it all server side if you want to. Have a look at the qSocks solution. The Engine API allows you to work with data/hypercubes etc and the qSocks module puts a nice wrapper around it. You can use qSocks on nodejs or in the client. I've put a link below.

qSocks - http://branch.qlik.com/projects/showthread.php?289-QSocks-Engine-API-wrapper&highlight=qsocks

**Comment by countnazgul** [comment]
Hmmm how did i miss the qSocks :)

Thank you very much for the response (and for nodejs-qliksense in general)!

Stefan
