### ISSUE TITLE
require(["js/Qlik"])

### ISSUE THREAD

**Issue by balexbyrd** [switchnick/nodejs-qliksense#2]
@websy85 I'm trying to get this up and running in Qlik Sense Desktop 2.1.1 so I can test before promoting to a server environment. Please let me know if this is the correct workflow:
1. Input the correct app name and object ID in the script.js file
2. In the index.html file: src="http://localhost:4848/resources/assets/external/requirejs/require.js"
3. Navigate to the nodejs-qliksense folder and open a commande line > type node server
4. In a web browser, open localhost/3000

I'm getting a 'Uncaught Error: Script error for: js/qlik' which points to the require statement right before it loads the application. This leads me to believe it's authenticating OK it's just not opening qlik. 

Is this the right workflow or what should I be doing differently? Thanks in advance.

**Comment by websy85** [comment]
@balexbyrd Is the require.js file getting successfully loaded into the page? Sense Desktop is always anonymous so it definitely wont be an authentication thing.What does your script.js file look like?

**Comment by gabiQlik** [comment]
I'm having a similar issue.
@balexbyrd Did you mange to figure it out?

**Comment by fernandosmcit** [comment]
I'm having this issue too... Require.js is ok.
Any idea?

**Comment by websy85** [comment]
Hi @fernandosmcit, can you provide some information about your environment? Mainly, what your config looks like for the connection and if it's Qlik Sense Enterprise or Desktop. The more info you can give me, the better.
Thanks

**Comment by fernandosmcit** [comment]
Debugging the code I realized the baseUrl of require.config method was wrong.
The code provided by dev hub was invalid. Correcting this, the lib was loaded correctly.
Thanks, @websy85 !
